import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

/**
 * Resolves the platform-native crash-dump directory at Gradle evaluation time.
 *
 * Mirrors the runtime `resolveLogDir()` logic in `main.kt` so that `-XX:ErrorFile`
 * points to a `crashes/` subdirectory of the application log folder. Used only by the
 * `:run` task — packaged builds intentionally omit `-XX:ErrorFile` because the path
 * resolved here is the build host's `user.home`, which would never match the path on
 * an end-user's machine. Without the flag, HotSpot falls back to writing crash dumps
 * next to the launcher, which is correct on the target.
 */
fun resolveCrashDir(): String {
	val userHome = System.getProperty("user.home")
	val os = System.getProperty("os.name").lowercase()
	val logDir = when {
		os.contains("win") ->
			File(System.getenv("LOCALAPPDATA") ?: "$userHome/AppData/Local", "omnisign/logs")
		os.contains("mac") ->
			File(userHome, "Library/Logs/omnisign")
		else ->
			File(System.getenv("XDG_STATE_HOME") ?: "$userHome/.local/state", "omnisign")
	}
	return File(logDir, "crashes").absolutePath
}

/**
 * Normalizes a semver-like string to the three-component `MAJOR.MINOR.BUILD` format required by
 * Windows native installers (MSI/EXE). Pre-release suffixes (e.g. `-SNAPSHOT`) are stripped, and
 * missing components are padded with `0`.
 *
 * Examples: `"1"` → `"1.0.0"`, `"1.5"` → `"1.5.0"`, `"1.5.0-SNAPSHOT"` → `"1.5.0"`.
 */
fun String.toNativeDistributionVersion(): String {
    val parts = substringBefore("-").split(".").mapNotNull { it.toIntOrNull() }
    return listOf(
        parts.getOrElse(0) { 0 },
        parts.getOrElse(1) { 0 },
        parts.getOrElse(2) { 0 },
    ).joinToString(".")
}

plugins {
	alias(libs.plugins.kotlin.multiplatform)
	alias(libs.plugins.kotlin.serialization)
	alias(libs.plugins.compose.multiplatform)
	alias(libs.plugins.compose.compiler)
	alias(libs.plugins.ksp)
	alias(libs.plugins.kotest)
	alias(libs.plugins.lumo)
	alias(libs.plugins.decoroutinator)
	alias(libs.plugins.dokka)
}

version = project.findProperty("releaseVersion")?.toString() ?: "1.0.0"

/**
 * Fixed version stamped into the generated Wasm/JS npm package manifests.
 *
 * Deliberately decoupled from [Project.getVersion] (which tracks the `releaseVersion` property for
 * `BuildConfig` and the native distribution). The Kotlin toolchain records this value in the
 * committed `kotlin-js-store/wasm/package-lock.json`; if it followed the release version, every
 * release build would resolve a lock with a different `version` field and fail the
 * `kotlinWasmStorePackageLock` check. These workspace packages are internal to the build and never
 * published, so their manifest version is cosmetic and safe to keep constant.
 */
val wasmNpmPackageVersion = "1.0.0"

afterEvaluate {
	configurations.findByName("commonTestApi")?.dependencies?.removeIf {
		it.group == "io.kotest" && it.name == "kotest-assertions-core"
	}
}

configurations.findByName("commonTestApi")?.dependencies?.removeIf {
	it.group == "io.kotest" && it.name == "kotest-assertions-core"
}

/**
 * Generates a `BuildConfig.kt` source file that exposes the Gradle project
 * version and the resolved server URL to common Compose code, so both the JVM
 * desktop and the Wasm web target can read them without a JVM-only manifest
 * lookup. Mirrors the CLI module's `generateVersionProperties` precedent.
 */
val generateBuildConfig by tasks.registering {
	group = "build"
	description = "Generates BuildConfig.kt containing the project version and server URL."
	val versionValue = project.version.toString()
	val serverUrlValue = System.getenv("OMNISIGN_SERVER_URL") ?: ""
	val outputDir = layout.buildDirectory.dir("generated/buildConfig/commonMain/kotlin")
	inputs.property("version", versionValue)
	inputs.property("serverUrl", serverUrlValue)
	outputs.dir(outputDir)
	doLast {
		val file = outputDir.get().asFile.resolve("cz/pizavo/omnisign/BuildConfig.kt")
		file.parentFile.mkdirs()
		file.writeText(
			"""
				package cz.pizavo.omnisign

				/**
				 * Build-time constants generated by the Gradle `generateBuildConfig` task.
				 *
				 * Do not edit by hand; regenerated on every build from the project version
				 * and the OMNISIGN_SERVER_URL environment variable.
				 */
				internal object BuildConfig {
				    /** Application version, sourced from the Gradle `releaseVersion` project property. */
				    const val VERSION: String = "$versionValue"

				    /**
				     * Base URL for HTTP requests issued by the web target to the OmniSign server.
				     *
				     * Resolved from the OMNISIGN_SERVER_URL environment variable at build time.
				     * An empty string (the default when the env var is unset) means "same origin":
				     * the Ktor client treats request paths as relative to the browser's current
				     * origin, which is correct when the OmniSign server hosts both the web bundle
				     * and the /api/v1 routes.
				     *
				     * This is the build-time fallback. At runtime the web target first consults an
				     * optional web-config.json served next to the bundle and uses this constant only
				     * when that file is absent or leaves the URL unset, so an operator can retarget a
				     * pre-built bundle without recompiling. See cz.pizavo.omnisign.web.resolveServerBaseUrl.
				     */
				    const val SERVER_URL: String = "$serverUrlValue"
				}
			""".trimIndent(),
		)
	}
}

kotlin {
	jvm {
		kotlin.jvmToolchain {
			languageVersion.set(JavaLanguageVersion.of(25))
			vendor.set(JvmVendorSpec.JETBRAINS)
		}
		testRuns.configureEach {
			executionTask.configure { useJUnitPlatform() }
		}
	}
	
	@OptIn(ExperimentalWasmDsl::class)
	wasmJs {
		browser()
		binaries.executable()
		val npmPackageVersion = wasmNpmPackageVersion
		compilations.all {
			packageJson {
				version = npmPackageVersion
			}
		}
	}
	
	sourceSets {
		commonMain {
			kotlin.srcDir(generateBuildConfig)
		}
		commonMain.dependencies {
			implementation(libs.androidx.lifecycle.viewmodelCompose)
			implementation(libs.androidx.lifecycle.runtimeCompose)
			implementation(libs.compose.runtime)
			implementation(libs.compose.foundation)
			implementation(libs.compose.material)
			implementation(libs.compose.ui)
			implementation(libs.compose.ui.tooling)
			implementation(libs.compose.components.resources)
			
			implementation(projects.shared)

			implementation(libs.kotlinx.serialization.json)
			
			implementation(project.dependencies.platform(libs.koin.bom))
			implementation(libs.koin.compose)
			implementation(libs.koin.compose.viewmodel)
			
			implementation(libs.filekit.core)
			implementation(libs.filekit.dialogs.compose)
		}
		commonTest.dependencies {
			implementation(libs.kotest.engine)
			implementation(libs.kotest.core)
		}
		jvmTest.dependencies {
			implementation(libs.kotest.jvm.runner)
			implementation(libs.kotest.arrow)
			implementation(libs.kotest.decoroutinator)
			implementation(libs.mockk)
			implementation(libs.kotlinx.coroutines.test)
		}
		jvmMain.dependencies {
			implementation(compose.desktop.currentOs)
			implementation(libs.kotlinx.coroutines.swing)
			implementation(libs.pdfbox)
			implementation(libs.decoroutinator.jvm)
			implementation(libs.jbr.api)
			implementation(libs.logback)
		}
		wasmJsMain.dependencies {
			implementation(npm("mupdf", libs.versions.mupdf.get()))
		}
	}
}

/**
 * Lazily resolved JBR launcher from the Gradle toolchain registry.
 *
 * Used to ensure that both compilation and the Compose Desktop `run` task
 * execute on JetBrains Runtime, which provides the Custom Title Bar API.
 */
val jbrLauncher = javaToolchains.launcherFor {
	languageVersion.set(JavaLanguageVersion.of(25))
	vendor.set(JvmVendorSpec.JETBRAINS)
}

/**
 * Eagerly resolved path to the JBR installation, or `null` when JBR is not
 * available on this machine. When `null`, the Compose Desktop `run` and
 * packaging tasks will fail at execution time with a descriptive message.
 */
val jbrHomePath: String? = try {
	jbrLauncher.map { it.metadata.installationPath.asFile.absolutePath }.get()
} catch (_: Exception) {
	null
}

compose.resources {
	generateResClass = always
}

/**
 * JVM arguments shared by every way the desktop app is launched: the Compose
 * `application` `run` task, the Compose Hot Reload `hotRunJvm` / `hotRunJvmAsync`
 * tasks (what the IDE "Run with Compose Hot Reload" gutter invokes), and the packaged
 * distribution.  Kept as a single source so the Hot Reload run can never silently
 * drift from `run` and drop `--add-opens` / `--enable-native-access` — that drift is
 * exactly what left the JDK PC/SC stale-context recovery unable to work under hot
 * reload.
 */
val desktopJvmArgs: List<String> = buildList {
	add("--enable-native-access=ALL-UNNAMED")
	add("--add-modules=java.smartcardio")
	add("--add-opens=java.smartcardio/sun.security.smartcardio=ALL-UNNAMED")
	add("-Dsun.java2d.d3d=false")
	add("-Dsun.awt.wmclass=OmniSign")
	if (org.gradle.internal.os.OperatingSystem.current().isLinux) {
		add("--add-opens")
		add("java.desktop/sun.awt.X11=ALL-UNNAMED")
	}
}

/**
 * Package metadata shared by the Compose DSL and the hand-rolled Linux installer tasks.
 *
 * The DEB and RPM are built by [LinuxInstallerTask] rather than by the Compose plugin (see its
 * KDoc), so every value both of them need is declared once here. Letting the two copies drift
 * would ship a DEB whose description or vendor disagrees with the MSI built from the same commit.
 */
val appDescription = "Digital signature verification, signing and re-timestamping"

/** Vendor recorded in every package. */
val appVendor = "Pizavo"

/** Copyright line recorded in every package. */
val appCopyright = "Copyright (C) 2026 Pizavo"

/** Documentation URL passed to jpackage as `--about-url`. */
val appAboutUrl = "https://pizavo.github.io/omnisign/desktop/"

/** Name of the DEB/RPM package itself, which also fixes the install prefix at `/opt/omnisign`. */
val linuxPackageName = "omnisign"

/** Freedesktop category the desktop entry is filed under. */
val linuxAppCategory = "utils"

/** Menu group the desktop entry appears in. */
val linuxMenuGroup = "Utility"

/** Maintainer recorded in the DEB control file. */
val debMaintainer = "pizavo@gmail.com"

/** Licence identifier recorded in the RPM spec. */
val rpmLicenseType = "AGPL-3.0-or-later"

compose.desktop {
	application {
		mainClass = "cz.pizavo.omnisign.MainKt"

		jvmArgs(*desktopJvmArgs.toTypedArray())

		jbrHomePath?.let { javaHome = it }

		buildTypes.release.proguard {
			isEnabled.set(false)
		}

		nativeDistributions {
			modules(
				"java.instrument",
				"java.management",
				"java.naming",
				"java.net.http",
				"java.smartcardio",
				"java.sql",
				"java.xml",
				"java.xml.crypto",
				"jdk.crypto.cryptoki",
				"jdk.unsupported",
			)
			
			if (org.gradle.internal.os.OperatingSystem.current().isWindows) {
				modules("jdk.crypto.mscapi")
			}

			if (org.gradle.internal.os.OperatingSystem.current().isLinux) {
				modules("jdk.security.auth")
			}
			
			targetFormats(
				TargetFormat.Msi,
				TargetFormat.Exe,

				TargetFormat.Dmg,
				TargetFormat.Pkg,

				TargetFormat.AppImage
			)
			packageName = "OmniSign"
			packageVersion = project.version.toString().toNativeDistributionVersion()
			description = appDescription
			vendor = appVendor
			copyright = appCopyright
			licenseFile.set(rootProject.layout.buildDirectory.file("legal/installer-license-desktop.md"))

			appResourcesRootDir.set(layout.buildDirectory.dir("appResources"))

			windows {
				iconFile.set(rootProject.file("assets/icons/omnisign-logo.ico"))
				shortcut = true
				menu = true
				menuGroup = "OmniSign"
				dirChooser = true
				perUserInstall = true
				upgradeUuid = "e479b089-886d-4bb1-94dd-b73837d17c2c"
			}

			linux {
				iconFile.set(rootProject.file("assets/icons/omnisign-logo-512.png"))
			}

			macOS {
				iconFile.set(rootProject.file("assets/icons/omnisign-logo.icns"))
				dockName = "OmniSign"
				bundleID = "cz.pizavo.omnisign.desktop"
				appCategory = "public.app-category.utilities"
			}
		}
	}
}

/**
 * Injects additional jpackage metadata arguments into every Compose Desktop packaging task.
 * The Compose Gradle plugin does not expose DSL properties for about-url or the Windows
 * help/update URLs, so the underlying [AbstractJPackageTask.freeArgs] list is used to pass them
 * to jpackage. Tasks that produce app-images (AppImage and Distributable) are excluded because
 * jpackage rejects installer-only options such as `--about-url` when `--type app-image` is used.
 * The Linux installers are not configured here at all — they are built by [LinuxInstallerTask],
 * which owns its whole argument list.
 *
 * On Windows every jpackage task additionally has [AbstractJPackageTask.packageDescription]
 * rewritten to the package name. jpackage stamps `--description` into the launcher
 * executable's `FileDescription` version-resource field, and Windows reads `FileDescription`
 * as the friendly application name — it is the label the shell shows in its "Open with" menu,
 * and the one Task Manager and the file's Details tab display — so the long package
 * description would stand in for the product name there. No task can be left out: each one
 * builds, and therefore stamps, its own app-image instead of reusing the distributable. The
 * remaining Windows readers of `--description` follow the same value, which reads correctly
 * for all of them: WiX `ARPCOMMENTS`, the MSI package description, and the self-extracting
 * installer's own `Installer of ...` description. Rewriting the task property is what makes
 * this work — appending `--description` to [AbstractJPackageTask.freeArgs] cannot, because
 * free args are emitted ahead of the plugin's own arguments and jpackage resolves a repeated
 * option to its last occurrence. Linux and macOS keep the long description.
 */
afterEvaluate {
	tasks.withType<org.jetbrains.compose.desktop.application.tasks.AbstractJPackageTask>().configureEach {
		if (org.gradle.internal.os.OperatingSystem.current().isWindows) {
			packageDescription.set(packageName)
		}

		if (name.contains("AppImage", ignoreCase = true) || name.contains("Distributable", ignoreCase = true)) return@configureEach

		freeArgs.addAll(
			"--about-url", appAboutUrl,
			"--file-associations", project.file("file-associations/pdf.properties").absolutePath,
		)
		if (name.contains("Msi", ignoreCase = true) || name.contains("Exe", ignoreCase = true)) {
			freeArgs.addAll(
				"--win-help-url", appAboutUrl,
				"--win-update-url", "https://github.com/pizavo/omnisign/releases",
			)
		}
	}
}

/**
 * Packages the app-image `createDistributable` produces into a Linux DEB or RPM.
 *
 * The Compose plugin's own DEB and RPM bundlers cannot build these, which is why
 * `TargetFormat.Deb` and `TargetFormat.Rpm` are absent from `targetFormats` above — dropping the
 * two formats also frees the `packageDeb` and `packageRpm` task names, which the tasks registered
 * below take over. jpackage needs
 * `--resource-dir packaging/linux` to pick up the desktop-entry and packaging-script overrides —
 * `OmniSign.desktop` supplies `Exec=APPLICATION_LAUNCHER %U` (without a field code the shell
 * cannot hand a PDF to the launcher at all), `StartupWMClass=OmniSign` to match the WM_CLASS
 * `main.kt` forces, and `StartupNotify=true`; `omnisign.spec` and `postinst` / `prerm` install the
 * AppStream metainfo and the hicolor icon. The plugin emits its own `--resource-dir` pointing at
 * `build/compose/tmp/resources`, and it emits it *after* [AbstractJPackageTask.freeArgs]; since
 * jpackage resolves a repeated option to its last occurrence, anything passed through `freeArgs`
 * is discarded. That directory is only ever populated on macOS, so on Linux the plugin hands
 * jpackage an empty override directory and wins. Nothing in the plugin's API can reorder the two:
 * `makeArgs` always emits `freeArgs` first, and `run` clears the directory and execs jpackage
 * inside a single `@TaskAction`, so no `doFirst` can stage files into it.
 *
 * Building from a finished app-image sidesteps all of it and keeps the arguments small, since
 * everything application-level is already baked into the image. This mirrors how `:cli` packages
 * itself, which passes `--resource-dir` exactly once and is unaffected by the same defect.
 */
abstract class LinuxInstallerTask @Inject constructor(private val execOps: ExecOperations) : DefaultTask() {

	/** Path to the jpackage binary of the JDK the Compose plugin builds the app-image with. */
	@get:Input
	abstract val jpackageBin: Property<String>

	/** Directory `createDistributable` writes into; it holds exactly one app-image directory. */
	@get:InputDirectory
	abstract val appImageRootDir: DirectoryProperty

	/** jpackage `--type` value: `deb` or `rpm`. */
	@get:Input
	abstract val packageType: Property<String>

	/** Directory jpackage writes the finished package into. */
	@get:OutputDirectory
	abstract val destDir: DirectoryProperty

	/**
	 * Directory holding the jpackage resource overrides.
	 *
	 * Declared as an input so Gradle reruns the task whenever the desktop entry, the RPM spec or
	 * either maintainer script changes.
	 */
	@get:InputDirectory
	abstract val resourceDir: DirectoryProperty

	/** Licence the installer presents, generated by the root `:generateInstallerLicense` task. */
	@get:InputFile
	abstract val licenseFile: RegularFileProperty

	/** Property file describing the PDF file association. */
	@get:InputFile
	abstract val fileAssociations: RegularFileProperty

	/** Arguments shared by both Linux package types. */
	@get:Input
	abstract val commonArgs: ListProperty<String>

	/** Arguments that apply to one package type only. */
	@get:Input
	abstract val extraArgs: ListProperty<String>

	/**
	 * Resolves the app-image and hands it to jpackage.
	 *
	 * The package name is taken from the app-image directory rather than repeated as a literal, so
	 * it cannot drift from the `packageName` the Compose DSL gave the launcher.
	 */
	@TaskAction
	fun pack() {
		val root = appImageRootDir.get().asFile
		val appImage = root.listFiles()?.singleOrNull { it.isDirectory }
			?: error("Expected exactly one app-image directory in $root, found ${root.list()?.joinToString()}")

		val dest = destDir.get().asFile
		dest.deleteRecursively()
		dest.mkdirs()

		execOps.exec {
			executable(jpackageBin.get())
			args(
				listOf(
					"--type", packageType.get(),
					"--app-image", appImage.absolutePath,
					"--name", appImage.name,
					"--dest", dest.absolutePath,
					"--license-file", licenseFile.get().asFile.absolutePath,
					"--file-associations", fileAssociations.get().asFile.absolutePath,
					"--resource-dir", resourceDir.get().asFile.absolutePath,
				) + commonArgs.get() + extraArgs.get()
			)
		}
	}
}

/** jpackage arguments both Linux package types share. */
val linuxCommonJpackageArgs: List<String> = listOf(
	"--app-version", project.version.toString().toNativeDistributionVersion(),
	"--description", appDescription,
	"--vendor", appVendor,
	"--copyright", appCopyright,
	"--about-url", appAboutUrl,
	"--linux-package-name", linuxPackageName,
	"--linux-app-category", linuxAppCategory,
	"--linux-menu-group", linuxMenuGroup,
	"--linux-shortcut",
)

/**
 * Registers the two Linux installer tasks and joins them to the plugin's per-OS aggregate.
 *
 * Deferred to [Project.afterEvaluate] because the Compose plugin creates `createDistributable` in
 * an `afterEvaluate` block of its own, and both tasks derive their app-image directory and their
 * jpackage binary from it — the latter so the installers are built with the same JDK (the JBR the
 * `application` block selects) that produced the image.
 *
 * They take the `packageDeb` / `packageRpm` names the dropped target formats left free, so that
 * they read as part of the same family as `packageMsi`, `packageExe`, `packageDmg` and
 * `packagePkg` instead of introducing a second naming scheme for one platform — and so that the
 * name cannot be confused with `:cli`'s unrelated `jpackageDeb` / `jpackageRpm`. Restoring either
 * target format then fails the build on a duplicate task name instead of silently shadowing these.
 *
 * `packageDistributionForCurrentOS` is wired from `targetFormats` alone, so on Linux it now stops
 * at the app-image; the [dependsOn] below carries it through to the installers again. Its release
 * counterpart is deliberately left alone, as it packages the minified `createReleaseDistributable`
 * image these tasks do not build from.
 *
 * `--linux-package-deps xdg-utils` is deliberately **not** passed, even though the generated
 * maintainer scripts call `xdg-desktop-menu` and `xdg-mime`. Because these tasks request desktop
 * integration, jpackage already derives that dependency for both formats on its own; passing it
 * again lists `xdg-utils` twice in the DEB's `Depends` field and adds nothing to the RPM's
 * `Requires`. Both tasks are disabled off Linux, where jpackage cannot build a DEB or RPM at all,
 * mirroring how the Compose plugin gates its own packaging tasks.
 *
 * The RPM build logs `Warning: app-image dir not generated by jpackage.` even for an image
 * jpackage itself produced. It comes from the RPM bundler alone — the DEB build of the same image
 * is silent, and it is not order-dependent — and the package is correct regardless, since the name
 * and version come from the arguments above rather than from the image's own metadata.
 */
afterEvaluate {
	val createDistributableTask =
		tasks.named<org.jetbrains.compose.desktop.application.tasks.AbstractJPackageTask>("createDistributable")

	fun registerLinuxInstallerTask(name: String, description: String, type: String, extraArgsList: List<String>) {
		tasks.register<LinuxInstallerTask>(name) {
			this.group = "distribution"
			this.description = description
			enabled = org.gradle.internal.os.OperatingSystem.current().isLinux
			dependsOn(createDistributableTask, ":generateInstallerLicense")
			jpackageBin.set(createDistributableTask.flatMap { it.javaHome }.map { "$it/bin/jpackage" })
			appImageRootDir.set(createDistributableTask.flatMap { it.destinationDir })
			packageType.set(type)
			destDir.set(layout.buildDirectory.dir("compose/binaries/main/$type"))
			resourceDir.set(layout.projectDirectory.dir("packaging/linux"))
			licenseFile.set(rootProject.layout.buildDirectory.file("legal/installer-license-desktop.md"))
			fileAssociations.set(layout.projectDirectory.file("file-associations/pdf.properties"))
			commonArgs.set(linuxCommonJpackageArgs)
			extraArgs.set(extraArgsList)
		}
	}

	registerLinuxInstallerTask(
		name = "packageDeb",
		description = "Packages the desktop app as a Debian/Ubuntu .deb from the app-image.",
		type = "deb",
		extraArgsList = listOf("--linux-deb-maintainer", debMaintainer),
	)

	registerLinuxInstallerTask(
		name = "packageRpm",
		description = "Packages the desktop app as a Red Hat/Fedora .rpm from the app-image.",
		type = "rpm",
		extraArgsList = listOf("--linux-rpm-license-type", rpmLicenseType),
	)

	if (org.gradle.internal.os.OperatingSystem.current().isLinux) {
		tasks.named("packageDistributionForCurrentOS") {
			dependsOn("packageDeb", "packageRpm")
		}
	}
}

/**
 * Adds `-XX:ErrorFile` to the `:run` JavaExec task only. The path is resolved from the
 * Gradle-running user's `user.home`, which on a developer's machine matches the runtime
 * user. Packaged jpackage builds intentionally omit this option (see [resolveCrashDir]).
 */
afterEvaluate {
	tasks.matching { it.name == "run" }.configureEach {
		(this as? JavaExec)?.jvmArgs("-XX:ErrorFile=${resolveCrashDir()}/hs_err_pid%p.log")
	}
}

/**
 * Compose Hot Reload's `hotRunJvm` task — `org.jetbrains.compose.reload.gradle.ComposeHotRun`,
 * a `JavaExec` — is what the IDE "Run with Compose Hot Reload" gutter and the
 * checked-in `.run/composeApp [Hot Reload]` configuration invoke.  It forks the
 * application JVM itself and does **not** inherit `compose.desktop.application`
 * `jvmArgs`, so without this it launches the app without `--add-opens` /
 * `--enable-native-access`, silently disabling JDK PC/SC stale-context recovery and
 * native access under hot reload.  Give it the same [desktopJvmArgs] as every other
 * launch path.
 *
 * Only the synchronous `hotRunJvm` is configured: its `[Async]` sibling
 * `hotRunJvmAsync` is a different type (`ComposeHotAsyncRun`, not a `JavaExec`) that
 * the IDE gutter does not use.  The non-null `as JavaExec` cast is deliberate — if a
 * future Compose release changes `hotRunJvm`'s type this fails the build loudly
 * rather than silently regressing the flags again.
 */
afterEvaluate {
	tasks.matching { it.name == "hotRunJvm" }.configureEach {
		(this as JavaExec).jvmArgs(desktopJvmArgs)
	}
}

gradle.taskGraph.whenReady {
	if (jbrHomePath != null) return@whenReady

	val needsJbr = allTasks.any {
		it.project.path == ":composeApp" && (
			it.name == "run" ||
			it.name == "suggestRuntimeModules" ||
			it.name.startsWith("package") ||
			it.name.contains("Distributable")
		)
	}

	if (needsJbr) {
		throw GradleException(
			buildString {
				appendLine()
				appendLine("JetBrains Runtime (JBR) 25 is required to build/run the desktop application")
				appendLine("but was not found by the Gradle toolchain resolver.")
				appendLine()
				appendLine("Install it via one of:")
				appendLine("  • IntelliJ IDEA → Settings → Build → Build Tools → Gradle → Gradle JDK")
				appendLine("  • Download from https://github.com/JetBrains/JetBrainsRuntime/releases")
				appendLine("    and place it under ~/.jdks/ so Gradle auto-detects it.")
			}
		)
	}
}

/**
 * On Linux, installs two user-local `.desktop` entries before every `:composeApp:run`.
 *
 * GNOME Shell (Wayland) matches XWayland windows to apps via two mechanisms:
 *  1. **`StartupWMClass` index** — only rebuilt at session login on Wayland.
 *  2. **Name lookup**: `appSys.lookup_app("omnisign.desktop")` — lowercase of
 *     WM_CLASS (`"OmniSign"` → `"omnisign"`), backed by GLib's `GAppInfoMonitor`
 *     (inotify) and effective **without a session restart**.
 *
 * Both files are written so icon matching works whether the user has ever
 * logged out since the project was cloned. No `sudo` is required; user-level
 * entries take precedence over any system-level RPM file.
 *
 * The task is **incremental**: it is skipped entirely on subsequent runs once the
 * files are up to date, adding zero overhead to day-to-day `:run` invocations.
 */
if (org.gradle.internal.os.OperatingSystem.current().isLinux) {
	val userAppsDir = file("${System.getProperty("user.home")}/.local/share/applications")
	val iconPath = rootProject.file("assets/icons/omnisign-logo-512.png").absolutePath

	val primaryContent =
		"[Desktop Entry]\n" +
		"Name=OmniSign\n" +
		"Comment=Digital signature verification, signing and re-timestamping\n" +
		"Exec=/opt/omnisign/bin/OmniSign\n" +
		"Icon=$iconPath\n" +
		"Terminal=false\n" +
		"Type=Application\n" +
		"Categories=Utility\n" +
		"MimeType=application/pdf\n" +
		"StartupWMClass=OmniSign\n" +
		"StartupNotify=true\n"

	val hiddenContent =
		"[Desktop Entry]\n" +
		"Name=OmniSign\n" +
		"Comment=OmniSign window-tracker entry — do not remove\n" +
		"Exec=true\n" +
		"Icon=$iconPath\n" +
		"Terminal=false\n" +
		"Type=Application\n" +
		"NoDisplay=true\n" +
		"StartupWMClass=OmniSign\n" +
		"StartupNotify=true\n"

	val primaryFile = userAppsDir.resolve("omnisign-OmniSign.desktop")
	val hiddenFile  = userAppsDir.resolve("omnisign.desktop")

	val installLinuxDevDesktopEntry by tasks.registering {
		group = "compose desktop"
		description =
			"Installs two user-local .desktop entries so GNOME Shell matches the running " +
			"window (WM_CLASS=OmniSign) to the correct icon when launching via :run."

		inputs.property("primaryContent", primaryContent)
		inputs.property("hiddenContent",  hiddenContent)
		outputs.files(primaryFile, hiddenFile)

		doLast {
			userAppsDir.mkdirs()
			primaryFile.writeText(primaryContent)
			hiddenFile.writeText(hiddenContent)

			try {
				ProcessBuilder("update-desktop-database", userAppsDir.absolutePath)
					.redirectErrorStream(true).start().waitFor()
			} catch (_: Exception) { /* may not be installed; inotify handles it */ }

			Thread.sleep(600)

			logger.lifecycle("Installed development .desktop entries in $userAppsDir")
		}
	}

	afterEvaluate {
		tasks.matching { it.name == "run" }.configureEach {
			dependsOn(installLinuxDevDesktopEntry)
		}
	}
}

/**
 * Dokka configuration for the composeApp module API documentation.
 * The wasmJs source set is suppressed because Dokka cannot fully process Wasm targets.
 */
dokka {
	dokkaPublications.html {
		outputDirectory.set(layout.buildDirectory.dir("dokka/html"))
	}
	pluginsConfiguration.html {
		footerMessage.set("OmniSign — composeApp module API reference")
	}
	dokkaSourceSets.configureEach {
		if (name.contains("wasmJs", ignoreCase = true) || name.contains("web", ignoreCase = true)) {
			suppress.set(true)
		}
	}
}

/**
 * Stages everything jpackage should place under the installed app's `resources/`
 * directory: the module's own platform resources plus the legal files that must
 * accompany the distribution.
 *
 * The desktop packages ship every dependency as a separate jar, and most of those
 * jars carry no licence text of their own — EU DSS, the library OmniSign is built
 * on, is the notable one. Installing `THIRD-PARTY.md` and `licenses/` alongside the
 * application is what satisfies the "supply a copy of this License" duty that the
 * LGPL and MPL components impose, and is where the in-app Credits dialog tells the
 * user to look.
 */
val assembleAppResources by tasks.registering(Sync::class) {
	group = "distribution"
	description = "Stages platform resources and the third-party legal files for jpackage."

	into(layout.buildDirectory.dir("appResources"))
	from(layout.projectDirectory.dir("resources"))
	from(rootProject.file("LICENSE.md")) { into("common") }
	from(rootProject.file("NOTICE.md")) { into("common") }
	from(rootProject.file("THIRD-PARTY.md")) { into("common") }
	from(rootProject.file("licenses")) { into("common/licenses") }
}

tasks.matching { it.name == "prepareAppResources" }.configureEach {
	dependsOn(assembleAppResources)
}

/**
 * The installer licence is generated by the root project (it summarises the third-party
 * components the package installs), so every task that hands a licence file to jpackage
 * has to wait for it.
 *
 * Matched by task *type*, not by name. `licenseFile` is set once on `nativeDistributions`, which
 * makes it a declared input of every [org.jetbrains.compose.desktop.application.tasks.AbstractJPackageTask] —
 * `createDistributable` included, even though an app image never shows a licence. Gradle validates
 * that input before running the task, so a missing file fails the build regardless of whether the
 * task would have used it. A `name.startsWith("package")` filter misses `createDistributable`
 * precisely, and that is the task CI builds.
 */
tasks.withType<org.jetbrains.compose.desktop.application.tasks.AbstractJPackageTask>().configureEach {
	dependsOn(":generateInstallerLicense")
}

/**
 * Writes the coordinates of everything the web target ships to a file the root
 * `:generateThirdPartyNotices` task reads.
 *
 * The Wasm variants cannot be resolved from the root project the way the JVM ones are:
 * Kotlin publishes them under its own usage value and target attribute, and a consumer
 * configured for them can no longer select the dependency BOMs the graph relies on.
 * Letting `:composeApp` resolve its own `wasmJsRuntimeClasspath` sidesteps that entirely,
 * and this task's output is an ordinary file input for the generator.
 */
val collectWebRuntimeCoordinates by tasks.registering {
	group = "documentation"
	description = "Records the Wasm runtime classpath coordinates for the third-party notices."

	val artifacts = configurations.named("wasmJsRuntimeClasspath")
		.flatMap { it.incoming.artifacts.resolvedArtifacts }
	val outputFile = layout.buildDirectory.file("notices/web-coordinates.txt")
	outputs.file(outputFile)

	doLast {
		val coordinates = artifacts.get()
			.map { it.id.componentIdentifier }
			.filterIsInstance<ModuleComponentIdentifier>()
			.map { "${it.group}:${it.module}:${it.version}" }
			.distinct()
			.sorted()
		outputFile.get().asFile.writeText(coordinates.joinToString("\n"))
		logger.lifecycle("Recorded ${coordinates.size} web runtime artifacts.")
	}
}

/**
 * Copies the third-party legal files into the WebAssembly distribution.
 *
 * The web bundle is a directory of static files rather than an installer, so it has no
 * `resources/` folder to piggyback on. Without this the Credits dialog would point web
 * users at a licences folder that does not exist, and the AGPL and MPL components the
 * bundle carries — MuPDF among them — would ship with no licence text at all.
 */
val bundleWebLegalFiles by tasks.registering(Copy::class) {
	group = "distribution"
	description = "Adds the third-party legal files to the web distribution."

	from(rootProject.file("LICENSE.md"))
	from(rootProject.file("NOTICE.md"))
	from(rootProject.file("THIRD-PARTY.md"))
	from(rootProject.file("licenses")) { into("licenses") }
	into(layout.buildDirectory.dir("dist/wasmJs/productionExecutable"))
}

tasks.matching { it.name == "wasmJsBrowserDistribution" }.configureEach {
	finalizedBy(bundleWebLegalFiles)
}
