changelog:
  categories:
    - title: New Features
      labels:
        - enhancement
        - server
    - title: Bug Fixes
      labels:
        - bug
        - server
    - title: Other Changes
      labels:
        - server
