changelog:
  categories:
    - title: New Features
      labels:
        - enhancement
        - cli
    - title: Bug Fixes
      labels:
        - bug
        - cli
    - title: Other Changes
      labels:
        - cli
