changelog:
  categories:
    - title: New Features
      labels:
        - enhancement
        - desktop
    - title: Bug Fixes
      labels:
        - bug
        - desktop
    - title: Other Changes
      labels:
        - desktop
