import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  developmentSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {
      type: 'link',
      label: 'API Reference',
      href: 'https://pizavo.github.io/omnisign/api/',
    },
  ],
};

export default sidebars;
