package cz.pizavo.omnisign.auth

import kotlin.time.Duration

/**
 * Server-side store of in-flight [LoginRequest]s, keyed by the OAuth2 `state` parameter.
 *
 * Exists because the OAuth2 authorization-code flow gives the server exactly one channel that
 * survives the trip out to the identity provider and back: `state`. The IdP echoes it on the
 * callback and nothing else the client sent.
 *
 * The obvious place to put this would be alongside the PKCE verifier, which is already keyed by
 * `state` — but that row is consumed inside the `oauth { providerLookup }` block, which Ktor runs
 * *before* the callback route handler, to feed `code_verifier` into the token exchange. By the
 * time the handler could read it, it is gone. Hence a second store with the same key and a
 * slightly longer reach.
 *
 * Rows are single-use: [consume] deletes atomically, so a replayed callback URL finds nothing.
 *
 * All methods are suspending so backing stores can use coroutine-friendly I/O.
 */
interface LoginRequestStore {

    /**
     * Park [request] under [state] for [ttl].
     *
     * @param state OAuth2 `state` parameter generated by Ktor's NonceManager for this flow.
     * @param request What the browser asked for on the way out.
     * @param ttl How long the row remains claimable — the same order as the PKCE verifier's
     *   lifetime, since it covers the same round trip.
     */
    suspend fun put(state: String, request: LoginRequest, ttl: Duration)

    /**
     * Atomically look up and remove the request parked under [state].
     *
     * @param state The `state` echoed back by the identity provider on the callback.
     * @return The parked [LoginRequest], or `null` when the flow was not a hand-off, has
     *   expired, or has already been claimed.
     */
    suspend fun consume(state: String): LoginRequest?

    /**
     * Delete every row whose expiry is in the past.
     *
     * @return The number of rows pruned.
     */
    suspend fun pruneExpired(): Int
}
